{% set name = "platformio" %}
{% set version = "6.1.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 79387b45ca7df9c0c51cae82b3b0a40ba78d11d87cea385db47e1033d781e959

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - platformio = platformio.__main__:main
    - pio = platformio.__main__:main
    - piodebuggdb = platformio.__main__:debug_gdb_main

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - bottle 0.13
    - click >=8.0.4,<9.0.0a0
    - colorama
    - marshmallow 3
    - pyelftools >0.27,<1.0a0
    - pyserial 3.5.*
    - requests 2.*
    - semantic_version 2.10.*
    - tabulate 0.*
    - aiofiles >=0.8.0
    - ajsonrpc 1.2.*
    - starlette >=0.19,<0.40a
    - uvicorn >=0.16,<0.31
    - wsproto 1

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - platformio
  commands:
    - pip check
    - platformio --help
    - pio --help

about:
  home: https://platformio.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PlatformIO is a new generation ecosystem for embedded development.
  dev_url: https://github.com/platformio/platformio-core

extra:
  recipe-maintainers:
    - hmaarrfk
