{% set name = "platformio" %}
{% set version = "6.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: eb10837cd2e485b0cc6abb0f76fc8ba1211caad4405fe9227450cb5a5267d593

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - platformio = platformio.__main__:main
    - pio = platformio.__main__:main
    - piodebuggdb = platformio.__main__:debug_gdb_main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - bottle 0.12
    - click >=8.0.4,<9,!=8.0.2
    - colorama
    - marshmallow 3
    - pyelftools >=0.27,<1
    - pyserial 3
    - requests 2
    - semantic_version 2.10
    - tabulate 0.8
    - zeroconf >=0.37,<1.0a
    - aiofiles 0.8
    - ajsonrpc 1
    - starlette 0.20
    - uvicorn 0.18
    - wsproto 1.1

test:
  requires:
    - pip
  imports:
    - platformio
  commands:
    - pip check
    - platformio --help
    - pio --help

about:
  home: https://platformio.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PlatformIO is a new generation ecosystem for embedded development.
  dev_url: https://github.com/platformio/platformio-core

extra:
  recipe-maintainers:
    - hmaarrfk
