{% set name = "platformio" %}
{% set version = "6.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8a4f660bd46f54d6b7271636be93019ec3c1f8ee547250c006661abde2f0946a
  patches:
    # 2021/12/30 hmaarrfk: I really don't think they have a hard requirement on
    # zeroconf. Their update just said "bump_dependencies" when they moved
    # from 0.37 to 0.38
    - zeroconf_dep.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - platformio = platformio.__main__:main
    - pio = platformio.__main__:main
    - piodebuggdb = platformio.__main__:debug_gdb_main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - bottle 0.12
    - click >=7.1.2,<9,!=8.0.2
    - colorama
    - pyserial >=3,!=3.3
    - requests >=2.4.0
    - semantic_version 2.9
    - tabulate >=0.8.3
    - pyelftools >=0.27,<1
    - marshmallow >=2,<4
    - zeroconf >=0.37
    - aiofiles 0.8
    - ajsonrpc 1
    - starlette 0.18
    - uvicorn 0.17
    - wsproto 1.0

test:
  requires:
    - pip
  imports:
    - platformio
  commands:
    - pip check
    - platformio --help
    - pio --help

about:
  home: https://platformio.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PlatformIO is a new generation ecosystem for embedded development.
  dev_url: https://github.com/platformio/platformio-core

extra:
  recipe-maintainers:
    - hmaarrfk
