{% set name = "platformio" %}
{% set version = "5.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 94584b1cfd8cc82ee5c51cbecba57e884f906b0c3f2903b136049796d62ae86a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - platformio = platformio.__main__:main
    - pio = platformio.__main__:main
    - piodebuggdb = platformio.__main__:debug_gdb_main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - bottle 0.12
    # PlatformIO specifies max versions of software that does not exist yet
    # I just removed the max version pinnings
    - click >=7.1.2,<9,!=8.0.2
    - colorama
    - pyserial >=3,!=3.3
    - requests >=2.4.0
    - semantic_version >=2.8.1
    - tabulate >=0.8.3
    - pyelftools >=0.27,<1
    - marshmallow >=2,<4
    - zeroconf
    - aiofiles 0.7
    - ajsonrpc 1
    - starlette 0.17
    - uvicorn 0.15
    - wsproto 1.0

test:
  requires:
    - pip
  imports:
    - platformio
  commands:
    - pip check
    - platformio --help
    - pio --help

about:
  home: https://platformio.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PlatformIO is a new generation ecosystem for embedded development.
  dev_url: https://github.com/platformio/platformio-core

extra:
  recipe-maintainers:
    - hmaarrfk
