{% set name = "platformio" %}
{% set version = "6.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9e72b94ff936bc530e80bef3f1ad5319d84fb4144bcf9587a4cc70ea6090ffce

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - platformio = platformio.__main__:main
    - pio = platformio.__main__:main
    - piodebuggdb = platformio.__main__:debug_gdb_main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - bottle 0.12
    - click >=8.0.4,<9,!=8.0.2
    - colorama
    - marshmallow 3.*
    - pyelftools >=0.27,<1
    - pyserial 3.*
    - requests 2.*
    - semantic_version 2.10.*
    - tabulate 0.9.*
    - zeroconf >=0.37,<1.0a
    - aiofiles 22.1.*
    - ajsonrpc 1.*
    - starlette 0.23.*
    - uvicorn 0.20.*
    - wsproto 1.2.*

test:
  requires:
    - pip
  imports:
    - platformio
  commands:
    - pip check
    - platformio --help
    - pio --help

about:
  home: https://platformio.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PlatformIO is a new generation ecosystem for embedded development.
  dev_url: https://github.com/platformio/platformio-core

extra:
  recipe-maintainers:
    - hmaarrfk
