{% set name = "platformio" %}
{% set version = "6.1.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7a88ce098f30c538fc0cf8f4c3ac4761c3c4b4eebf09fd3606f172399cd7d4e4

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - platformio = platformio.__main__:main
    - pio = platformio.__main__:main
    - piodebuggdb = platformio.__main__:debug_gdb_main

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - bottle 0.12
    - click 8.1.*
    - colorama
    - marshmallow 3.19.*
    - pyelftools 0.29
    - pyserial 3.5.*
    - requests 2.*
    - semantic_version 2.10.*
    - tabulate 0.*
    - aiofiles >=0.8.0
    - ajsonrpc 1.2.*
    - starlette 0.28.*
    - uvicorn 0.22.*
    - wsproto 1.2.*

test:
  requires:
    - pip
  imports:
    - platformio
  commands:
    - pip check
    - platformio --help
    - pio --help

about:
  home: https://platformio.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PlatformIO is a new generation ecosystem for embedded development.
  dev_url: https://github.com/platformio/platformio-core

extra:
  recipe-maintainers:
    - hmaarrfk
